[package]
name = "pdf_derive"
version = "0.1.15"
authors = ["Sebastian Köln <sebk@rynx.org>"]
homepage = "https://github.com/pdf-rs"
repository = "https://github.com/pdf-rs/pdf_derive"
license = "MIT"

[dependencies]
syn = "0.11.11"
quote = "0.3.15"

[lib]
proc-macro = true
