[package]
name = "pdf"
version = "0.6.2"
authors = ["Erlend Hofstad Langseth <3rlendhl@gmail.com>", "Sebastian Köln <sebk@rynx.org>"]
repository = "https://github.com/Ploppz/pdf-rs"
readme = "README.md"
keywords = ["pdf"]
license = "MIT"
documentation = "https://docs.rs/pdf/0.6.0/pdf/"

description = """
Read, alter and write PDF files.
(Crate that previously resided here moved to pdf-canvas)
"""


[dependencies.pdf_derive]
# git = "https://github.com/pdf-rs/pdf_derive.git"
path = "../derive"
version = "= 0.1.15"

[dependencies]
error-chain = "0.11.0"
isatty = "0.1"
num-traits = "0.1.36"
inflate = "0.1.1"
ansi_term = "0.9.0"
byteorder = "1.0.0"
itertools = "0.6.0"
ordermap = "0.2.9"
memmap = "0.5.2"
encoding = "0.2.33"
lzw = "0.10.0"
tuple = "0.1.7"
glob = "0.2.11"
chrono = "0.4.0"

[lib]
doctest = false

