[package]
name = "pdf"
version = "0.6.0"
authors = ["Erlend Hofstad Langseth <3rlendhl@gmail.com>"]

description = """
Read, alter and write PDF files.
(Crate that previously resided here moved to pdf-canvas)
"""

repository = "https://github.com/Ploppz/pdf-rs"
readme = "README.md"
keywords = ["pdf"]
license = "MIT"

[dependencies]
error-chain = "0.9.0"
isatty = "0.1"
num-traits = "*"
inflate = "0.1.1"
ansi_term = "0.9.0"

[lib]
doctest = false
