[workspace]
members = [
    "pdf",
    "pdf_derive",
    "view",
    "render",
    "examples/read",
    "examples/text",
    "examples/names",
]
default-members = [
    "pdf",
    "pdf_derive",
    "render"
   # "view"
]

#[patch."https://github.com/s3bk/vector"]
#vector = { path = "../vector" }

#[patch."https://github.com/pdf-rs/font"]
#font = { path = "../font" }

#[patch."https://github.com/s3bk/pathfinder_view"]
#pathfinder_view = { path = "../pathfinder_view" }
