[workspace]
members = [
    "pdf",
    "pdf_derive",
    "view",
    "render",
    "examples/read",
    "examples/text",
    "examples/names",
]
default-members = [
    "pdf",
    "pdf_derive",
    "render"
   # "view"
]

