[package]
name = "pdf"
version = "0.6.1"
authors = ["Erlend Hofstad Langseth <3rlendhl@gmail.com>"]

description = """
Read, alter and write PDF files.
(Crate that previously resided here moved to pdf-canvas)
"""

repository = "https://github.com/Ploppz/pdf-rs"
readme = "README.md"
keywords = ["pdf"]
license = "MIT"
documentation = "https://docs.rs/pdf/0.6.0/pdf/"

[dependencies.pdf_derive]
git = "https://github.com/pdf-rs/pdf_derive.git"
#path = "../pdf_derive"
version = "= 0.1.13"

[dependencies]
error-chain = "0.9.0"
isatty = "0.1"
num-traits = "0.1.36"
inflate = "0.1.1"
ansi_term = "0.9.0"
byteorder = "*"
itertools = "*"
ordermap = "*"
memmap = "*"
encoding = "*"
lzw = "*"
tuple = ">= 0.1.7"

[lib]
doctest = false
