[package]
name = "pdf"
version = "0.1.0"
authors = ["Erlend Hofstad Langseth <3rlendhl@gmail.com>"]

[dependencies]
error-chain = "0.9.0"
isatty = "0.1"
num-traits = "*"
inflate = "0.1.1"
ansi_term = "0.9.0"

[lib]
doctest = false
