[package]
name = "view"
version = "0.1.0"
authors = ["Sebastian Köln <sebk@rynx.org>"]
edition = "2018"

[features]
unstable = ["font/unstable"]

[dependencies]
pdf = { path = "../pdf" }
font = { git = "https://github.com/pdf-rs/font/" }
encoding = { git = "https://github.com/pdf-rs/encoding/" }

pathfinder_canvas = { git = "https://github.com/s3bk/pathfinder/" }
pathfinder_content = { git = "https://github.com/s3bk/pathfinder/" }
pathfinder_export = { git = "https://github.com/s3bk/pathfinder/" }
pathfinder_geometry = { git = "https://github.com/s3bk/pathfinder/" }
pathfinder_gl = { git = "https://github.com/s3bk/pathfinder/" }
pathfinder_gpu = { git = "https://github.com/s3bk/pathfinder/" }
pathfinder_renderer = { git = "https://github.com/s3bk/pathfinder/" }
vector = { git = "https://github.com/s3bk/vector/" }

euclid = "0.19"
log = "0.4.8"
env_logger = "*"
gl = "0.6"
sdl2 = "0.32"
sdl2-sys = "0.32"

[[bin]]
name = "pdf_view"

[[bin]]
name = "pdf2svg"
