[package]
name = "text"
version = "0.1.0"
authors = ["Erlend Hofstad Langseth <3rlendhl@gmail.com>", "Sebastian Köln <sebk@rynx.org>"]
edition = "2018"

[dependencies]
pdf = { path = "../../pdf" }
utf16-ext = "0.1.0"
byteorder = "1.2"